### ISSUE TITLE
Work w/ GeoPandas 0.8 or higher? 

### ISSUE THREAD

**Issue by nygeog** [apulverizer/allagash#19]
**Is your feature request related to a problem? Please describe.**
When installing w/ newer version of `geopandas` I had some conflicts, not sure whether to mark as bug or feature request. I can recreate the error when back in the office. I conda installed GeoPandas then `pip installed allagash` and when importing geopandas ```import geopandas``` had a failure on NB Series, error is this:

```
~\Anaconda3\envs\geospatial\lib\site-packages\geopandas\base.py in <module>
      4 import pandas as pd
      5 from pandas import Series, DataFrame, MultiIndex
----> 6 from pandas.core.indexing import _NDFrameIndexer
      7 from shapely.geometry import box, MultiPoint, MultiLineString, MultiPolygon
      8 from shapely.ops import cascaded_union, unary_union

ImportError: cannot import name '_NDFrameIndexer' from 'pandas.core.indexing' (C:\Users\{username}\Anaconda3\envs\geospatial\lib\site-packages\pandas\core\indexing.py)
```

**Describe the solution you'd like**
I'd like to be able to use later version of GeoPandas than 0.4.0. 

**Describe alternatives you've considered**
I haven't done any, I mostly want to test `allagash` out in my environment to see if I can add to my GIS python tools. 

**Additional context**

**Comment by apulverizer** [comment]
@nygeog If you create an new conda env and just install geopandas (don't install allagash) does that work? At first glance this seems like a geopandas/pandas version mismatch.

**Comment by apulverizer** [comment]
@nygeog  this should work now if you try installing again (version 0.2.1)

**Comment by apulverizer** [comment]
Verified this works with v0.2.1

**Comment by nygeog** [comment]
@apulverizer sorry on delay!!! Confirmed it works for me as well for `geopandas.__version__` '0.6.1' and `allagash.__version__` '0.2.1' - Thanks so much! :)
